server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: payment_routh                          # 路由的id 没有固定的规则 但要求唯一, 建议配合服务名
#         uri: http://localhost:8001                 # 匹配后提供服务的路由地址
         uri: lb://cloud-payment-service               # 匹配后提供服务的路由地址
         predicates:
           - Path=/payment/getPaymentById/**                  # 断言, 路径性匹配的进行路由
       - id: payment_routh2
         uri: lb://cloud-payment-service
#         uri: http://localhost:8001
         predicates:
           - Path=/payment/lb/**
#           - After=2021-07-12T17:28:57.437+08:00[Asia/Shanghai]
#           - Cookie=username,zzyy
#           - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性,且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka